SELECT IsNull( String( bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS_EXAMES.CODI_EMP), 'NULO'),
         IsNull( String( bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS_EXAMES.I_EMPREGADOS), 'NULO'), 
         IsNull( String( bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS_EXAMES.I_ATESTADO_OCUPACIONAL), 'NULO'), 
         IsNull( String( bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS_EXAMES.I_EXAME), 'NULO'),
         IsNull( String( bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS_EXAMES.DATA ), 'NULO'),
         IsNull( String( bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS_EXAMES.DESCRICAO), 'NULO'),
         IsNull( String( bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS_EXAMES.ORIGEM_REGISTRO), 'NULO'),
         IsNull( String( bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS_EXAMES.CODIGO_TUSS), 'NULO')

    FROM bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS_EXAMES
    
   WHERE bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS_EXAMES.CODI_EMP = '#codi_emp#'