SELECT COALESCE(STRING(bethadba.FOMEDICOS.I_MEDICOS), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.NOME), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.ORGAO_CLASSE), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.NUMERO_ORGAO_CLASSE), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.CODIGO_ESTADO), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.FORMA_CONTATO), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.TELEFONE), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.ORIGEM_REGISTRO), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.I_DADOS_EVENTOS_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.I_LOTE_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.STATUS_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.ENVIAR_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.INCLUSAO_VALIDADA_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.GERAR_RETIFICACAO_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.PROCESSAR_EXCLUSAO_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOMEDICOS.CPF), 'NULO')

FROM bethadba.FOMEDICOS

WHERE bethadba.FOMEDICOS.I_MEDICOS <> 0

ORDER BY bethadba.FOMEDICOS.I_MEDICOS