SELECT COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.CODI_EMP), 'NULO') AS field_1,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_DADOS_EVENTOS), 'NULO') AS field_2,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_LOTE), 'NULO') AS field_3,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.CODIGO_ESOCIAL), 'NULO') AS field_4,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_EVENTO_ESOCIAL), 'NULO') AS field_5,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.TIPO_ENVIO), 'NULO') AS field_6,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.TABELA_DADOS), 'NULO') AS field_7,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.CHAVE_TABELA_DADOS), 'NULO') AS field_8,
'conversao' AS field_9, /* field ID - conversao because sql dont delete esocial data */
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.XML_EVENTO), 'NULO') AS field_10,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.NUMERO_RECIBO), 'NULO') AS field_11,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_RESPOSTA), 'NULO') AS field_12,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.DESCRICAO_RESPOSTA), 'NULO') AS field_13,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.VALIDADO), 'NULO') AS field_14,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.AGUARDANDO_AJUSTE), 'NULO') AS field_15,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.DATA_HORA_CONCLUSAO), 'NULO') AS field_16,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.NOME_ARQUIVO), 'NULO') AS field_17,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.DATA_ALTERACAO), 'NULO') AS field_18,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_EVENTO_ESOCIAL_EXCLUIDO), 'NULO') AS field_19,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.NUMERO_RECIBO_EXCLUIDO), 'NULO') AS field_20,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.CODI_EMP_EVENTO_RETIFICADO), 'NULO') AS field_21,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_DADOS_EVENTOS_EVENTO_RETIFICADO), 'NULO') AS field_22,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.COMPETENCIA_CALCULO), 'NULO') AS field_23,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.GERAR_REMUNERACAO_13_SALARIO), 'NULO') AS field_24,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_RESPONSAVEL), 'NULO') AS field_25,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.EXISTE_MOVIMENTACAO_PERIODO), 'NULO') AS field_26,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_SERVICOS), 'NULO') AS field_27,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.TIPO_VALIDACAO), 'NULO') AS field_28,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.XML_ALTERADO), 'NULO') AS field_29,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.MOSTRAR_PAINEL_ESOCIAL), 'NULO') AS field_30,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.NIS_EMPREGADO), 'NULO') AS field_31,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.DATA_CRIACAO_REGISTRO), 'NULO') AS field_32,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.DATA_ALTERACAO_REGISTRO), 'NULO') AS field_33,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.DATA_PROCESSAMENTO_REGISTRO), 'NULO') AS field_34,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.VERSAO_SISTEMA), 'NULO') AS field_35,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.INCLUSAO_DUPLICADA), 'NULO') AS field_36,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.COMPETENCIA_REENVIAR_CALCULO_APOS_VALIDACAO), 'NULO') AS field_37,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.XSD_VALIDADO), 'NULO') AS field_38,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.INICIO_AFASTAMENTO), 'NULO') AS field_39,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.FIM_AFASTAMENTO), 'NULO') AS field_40,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.REENVIAR), 'NULO') AS field_41,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.GERAR_LIMPEZA_DADOS_ESOCIAL), 'NULO') AS field_42,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.COMPETENCIA_INICIO_VALIDADE), 'NULO') AS field_43,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.UTILITARIO_CONVERSAO_REGISTROS_ENVIADOS_OUTRO_BANCO), 'NULO') AS field_44,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.CODIGO_PROCESSO_AUDITOR), 'NULO') AS field_45,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.CANCELAMENTO_AVISO_PREVIO), 'NULO') AS field_46,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.ID_DUPLICADO_ALTERADO), 'NULO') AS field_47,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.ADVERTENCIA_AJUSTADA), 'NULO') AS field_48,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.POSSUI_VERBAS_RESCISORIAS_PERIODO), 'NULO') AS field_49,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.EMPRESA_RESPONSAVEL), 'NULO') AS field_50,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.VERSAO_LEIAUTE), 'NULO') AS field_51,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.ADMISSAO_TSVE_COM_MATRICULA), 'NULO') AS field_52,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.EXISTE_ENVIO_AQUISICAO_RURAL), 'NULO') AS field_53,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.EFETUAR_TRANSMISSAO_IMEDIATA_DCTFWEB), 'NULO') AS field_54,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.EXISTE_ENVIO_TREINAMENTOS), 'NULO') AS field_55,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.NUMERO_RECIBO_RETIFICACAO), 'NULO') AS field_56,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.REENVIAR_INVALIDADO), 'NULO') AS field_57,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.REENVIAR_EVENTO_AUTOMATICAMENTE), 'NULO') AS field_58

FROM bethadba.FOESOCIAL_DADOS_EVENTOS

WHERE bethadba.FOESOCIAL_DADOS_EVENTOS.codi_emp = '#codi_emp#'
  AND bethadba.FOESOCIAL_DADOS_EVENTOS.i_evento_esocial in (1000)
  AND bethadba.FOESOCIAL_DADOS_EVENTOS.i_dados_eventos = ( SELECT MIN(FOESOCIAL_DADOS_EVENTOS2.i_dados_eventos)
                                                             FROM bethadba.FOESOCIAL_DADOS_EVENTOS AS FOESOCIAL_DADOS_EVENTOS2
                                                            WHERE FOESOCIAL_DADOS_EVENTOS2.codi_emp = bethadba.FOESOCIAL_DADOS_EVENTOS.codi_emp
                                                              AND FOESOCIAL_DADOS_EVENTOS2.i_evento_esocial = 1000 )


UNION ALL


SELECT COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.CODI_EMP), 'NULO') AS field_1,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_DADOS_EVENTOS), 'NULO') AS field_2,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_LOTE), 'NULO') AS field_3,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.CODIGO_ESOCIAL), 'NULO') AS field_4,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_EVENTO_ESOCIAL), 'NULO') AS field_5,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.TIPO_ENVIO), 'NULO') AS field_6,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.TABELA_DADOS), 'NULO') AS field_7,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.CHAVE_TABELA_DADOS), 'NULO') AS field_8,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.ID), 'NULO') AS field_9, /* field ID - conversao because sql dont delete esocial data */
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.XML_EVENTO), 'NULO') AS field_10,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.NUMERO_RECIBO), 'NULO') AS field_11,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_RESPOSTA), 'NULO') AS field_12,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.DESCRICAO_RESPOSTA), 'NULO') AS field_13,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.VALIDADO), 'NULO') AS field_14,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.AGUARDANDO_AJUSTE), 'NULO') AS field_15,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.DATA_HORA_CONCLUSAO), 'NULO') AS field_16,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.NOME_ARQUIVO), 'NULO') AS field_17,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.DATA_ALTERACAO), 'NULO') AS field_18,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_EVENTO_ESOCIAL_EXCLUIDO), 'NULO') AS field_19,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.NUMERO_RECIBO_EXCLUIDO), 'NULO') AS field_20,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.CODI_EMP_EVENTO_RETIFICADO), 'NULO') AS field_21,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_DADOS_EVENTOS_EVENTO_RETIFICADO), 'NULO') AS field_22,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.COMPETENCIA_CALCULO), 'NULO') AS field_23,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.GERAR_REMUNERACAO_13_SALARIO), 'NULO') AS field_24,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_RESPONSAVEL), 'NULO') AS field_25,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.EXISTE_MOVIMENTACAO_PERIODO), 'NULO') AS field_26,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.I_SERVICOS), 'NULO') AS field_27,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.TIPO_VALIDACAO), 'NULO') AS field_28,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.XML_ALTERADO), 'NULO') AS field_29,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.MOSTRAR_PAINEL_ESOCIAL), 'NULO') AS field_30,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.NIS_EMPREGADO), 'NULO') AS field_31,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.DATA_CRIACAO_REGISTRO), 'NULO') AS field_32,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.DATA_ALTERACAO_REGISTRO), 'NULO') AS field_33,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.DATA_PROCESSAMENTO_REGISTRO), 'NULO') AS field_34,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.VERSAO_SISTEMA), 'NULO') AS field_35,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.INCLUSAO_DUPLICADA), 'NULO') AS field_36,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.COMPETENCIA_REENVIAR_CALCULO_APOS_VALIDACAO), 'NULO') AS field_37,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.XSD_VALIDADO), 'NULO') AS field_38,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.INICIO_AFASTAMENTO), 'NULO') AS field_39,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.FIM_AFASTAMENTO), 'NULO') AS field_40,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.REENVIAR), 'NULO') AS field_41,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.GERAR_LIMPEZA_DADOS_ESOCIAL), 'NULO') AS field_42,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.COMPETENCIA_INICIO_VALIDADE), 'NULO') AS field_43,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.UTILITARIO_CONVERSAO_REGISTROS_ENVIADOS_OUTRO_BANCO), 'NULO') AS field_44,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.CODIGO_PROCESSO_AUDITOR), 'NULO') AS field_45,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.CANCELAMENTO_AVISO_PREVIO), 'NULO') AS field_46,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.ID_DUPLICADO_ALTERADO), 'NULO') AS field_47,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.ADVERTENCIA_AJUSTADA), 'NULO') AS field_48,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.POSSUI_VERBAS_RESCISORIAS_PERIODO), 'NULO') AS field_49,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.EMPRESA_RESPONSAVEL), 'NULO') AS field_50,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.VERSAO_LEIAUTE), 'NULO') AS field_51,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.ADMISSAO_TSVE_COM_MATRICULA), 'NULO') AS field_52,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.EXISTE_ENVIO_AQUISICAO_RURAL), 'NULO') AS field_53,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.EFETUAR_TRANSMISSAO_IMEDIATA_DCTFWEB), 'NULO') AS field_54,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.EXISTE_ENVIO_TREINAMENTOS), 'NULO') AS field_55,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.NUMERO_RECIBO_RETIFICACAO), 'NULO') AS field_56,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.REENVIAR_INVALIDADO), 'NULO') AS field_57,
COALESCE(STRING(bethadba.FOESOCIAL_DADOS_EVENTOS.REENVIAR_EVENTO_AUTOMATICAMENTE), 'NULO') AS field_58

FROM bethadba.FOESOCIAL_DADOS_EVENTOS

WHERE bethadba.FOESOCIAL_DADOS_EVENTOS.codi_emp = '#codi_emp#'
  and (  bethadba.FOESOCIAL_DADOS_EVENTOS.i_evento_esocial in (1000,1005,1020,1030,1050,2200,2205,2206,2298,2299,2300,2306,2399)
     or  bethadba.FOESOCIAL_DADOS_EVENTOS.I_EVENTO_ESOCIAL_excluido in (1000,1005,1020,1030,1050,2200,2205,2206,2298,2299,2300,2306,2399) )
  AND bethadba.FOESOCIAL_DADOS_EVENTOS.i_dados_eventos <> ( SELECT MIN(FOESOCIAL_DADOS_EVENTOS2.i_dados_eventos)
                                                             FROM bethadba.FOESOCIAL_DADOS_EVENTOS AS FOESOCIAL_DADOS_EVENTOS2
                                                            WHERE FOESOCIAL_DADOS_EVENTOS2.codi_emp = bethadba.FOESOCIAL_DADOS_EVENTOS.codi_emp
                                                              AND FOESOCIAL_DADOS_EVENTOS2.i_evento_esocial = 1000 )

ORDER BY 1,2