SELECT IsNull( String( bethadba.FOHORARIOS.codi_emp ), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.I_HORARIO), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.NOME), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.DATA_INICIO), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.SITUACAO), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.DATA_INATIVACAO), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.TIPO), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.HORA_ENTRADA), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.HORA_SAIDA), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.TIPO_INTERVALO), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.DURACAO_INTERVALO), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.ORIGEM_REG), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.CODIGO_ESOCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.VARIACAO_DIARIA_ENTRADA_SAIDA), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.DURACAO_JORNADA), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.DURACAO_JORNADA_MINUTOS), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS.DURACAO_INTERVALO_MINUTOS), 'NULO')

    FROM bethadba.FOHORARIOS
    
   WHERE bethadba.FOHORARIOS.codi_emp = '#codi_emp#'

ORDER BY bethadba.FOHORARIOS.codi_emp ASC, 
         bethadba.FOHORARIOS.i_horario ASC