SELECT COALESCE(STRING(bethadba.FOESOCIAL_LOTES.CODI_EMP), 'NULO') AS field_1,
COALESCE(STRING(bethadba.FOESOCIAL_LOTES.I_LOTE), 'NULO') AS field_2,
COALESCE(STRING(bethadba.FOESOCIAL_LOTES.STATUS), 'NULO') AS field_3,
COALESCE(STRING(bethadba.FOESOCIAL_LOTES.I_EVENTO_ESOCIAL), 'NULO') AS field_4,
COALESCE(STRING(bethadba.FOESOCIAL_LOTES.VERSAO), 'NULO') AS field_5,
COALESCE(STRING(bethadba.FOESOCIAL_LOTES.LOTE_EXCLUSAO), 'NULO') AS field_6,
COALESCE(STRING(bethadba.FOESOCIAL_LOTES.DATA_CRIACAO_REGISTRO), 'NULO') AS field_7,
COALESCE(STRING(bethadba.FOESOCIAL_LOTES.DATA_ALTERACAO_REGISTRO), 'NULO') AS field_8,
COALESCE(STRING(bethadba.FOESOCIAL_LOTES.DATA_PROCESSAMENTO_REGISTRO), 'NULO') AS field_9,
COALESCE(STRING(bethadba.FOESOCIAL_LOTES.VERSAO_SISTEMA), 'NULO') AS field_10,
COALESCE(STRING(bethadba.FOESOCIAL_LOTES.POSSUI_EVENTOS_INVALIDADOS), 'NULO') AS field_11

FROM bethadba.FOESOCIAL_LOTES

WHERE bethadba.FOESOCIAL_LOTES.codi_emp = '#codi_emp#'
  and bethadba.FOESOCIAL_LOTES.i_evento_esocial in (1000,1005,1020,1030,1050,2200,2205,2206,2298,2299,2300,2306,2399,3000)

ORDER BY 1,2
