SELECT IsNull( String( bethadba.FOHORARIOS_INTERVALOS.codi_emp ), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS_INTERVALOS.I_HORARIO), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS_INTERVALOS.I_INTERVALO), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS_INTERVALOS.HORA_INICIO), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS_INTERVALOS.HORA_FIM), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS_INTERVALOS.INTERVALO_PRINCIPAL), 'NULO'),
        COALESCE(STRING(bethadba.FOHORARIOS_INTERVALOS.ORIGEM_REG), 'NULO')

    FROM bethadba.FOHORARIOS_INTERVALOS
    
   WHERE bethadba.FOHORARIOS_INTERVALOS.codi_emp = '#codi_emp#'

ORDER BY bethadba.FOHORARIOS_INTERVALOS.codi_emp ASC, 
         bethadba.FOHORARIOS_INTERVALOS.i_horario ASC