SELECT COALESCE( String( bethadba.FOVIGENCIAS_SERVICO.codi_emp ), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.i_servicos), 'NULO'),
        CASE WHEN fun.admissao IS NOT NULL AND fun.admissao < fovigencias_servico.vigencia THEN STRING(fun.admissao) ELSE STRING(fovigencias_servico.vigencia) END,
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.DESCRICAO), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.cgc), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.tipo_insc), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_terceiro), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.perc_terceiro), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.perc_inss_empresa), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.perc_acid_trabalho), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_sat), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.perc_autonomos), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_fpas), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_atividade), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_gfip), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_gps), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.i_bancos), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.numero_fgts), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.endereco), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.numero), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.bairro), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.cep), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.cidade), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.estado), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.i_filiais), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.sequencia_gps), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.filantropia), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.origem_reg), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.tipo), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codi_mun), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_municipio), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.I_FPAS), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.CALCULA_INSS_EMPRESA_LEI_12546), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_SERVICO_TOMADOR), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_ENDERECO), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.COMPLEMENTO), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_INSCRICAO_CONTRATANTE_EMPREITADA_PARCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.INSCRICAO_CONTRATANTE_EMPREITADA_PARCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.NOME_CONTRATANTE_EMPREITADA_PARCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_INSCRICAO_PROPRIETARIO_CEI_EMPREITADA_PARCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.INSCRICAO_PROPRIETARIO_CEI_EMPREITADA_PARCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.NOME_PROPRIETARIO_CEI_EMPREITADA_PARCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.I_CNAE20), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_INFORMACAO_ALIQUOTA_ACIDENTE_TRABALHO), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.I_PROCESSO), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.I_SCP), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.DDD), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TELEFONE), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.COMPETENCIA_FIM_VIGENCIA), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_LOTACAO_ESOCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.I_PROCESSO_TERCEIROS), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.CAEPF), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_CAEPF), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.REGISTRO_PONTO), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.CONTRATACAO_APRENDIZ), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.I_PROCESSO_CONTRATACAO_APRENDIZ), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.REALIZA_CONTRATACAO_APRENDIZ_INTERMEDIO_ENTIDADE_EDUCATIVA_SEM_FINS_LUCRATIVOS), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.CODIGO_SUSPENSAO_PROCESSO_RAT), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.SOMA_CODIGOS_SUSPENSAO_TERCEIROS), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.PERCENTUAL_TERCEIRO_BRUTO), 'NULO')

    FROM bethadba.FOVIGENCIAS_SERVICO
         LEFT OUTER JOIN bethadba.foempregados AS fun
                   ON    fun.codi_emp = fovigencias_servico.codi_emp
    
   WHERE bethadba.FOVIGENCIAS_SERVICO.codi_emp = '#codi_emp#'
     AND fovigencias_servico.vigencia = ( SELECT MIN(vig_2.vigencia)
                                            FROM bethadba.fovigencias_servico AS vig_2
                                           WHERE vig_2.codi_emp = fovigencias_servico.codi_emp
                                             AND vig_2.i_servicos = fovigencias_servico.i_servicos )
     AND ( fun.codi_emp IS NULL
           OR fun.i_empregados = ( SELECT MIN(fun_2.i_empregados)
                                     FROM bethadba.foempregados AS fun_2
                                    WHERE fun_2.codi_emp = fun.codi_emp
                                      AND fun_2.admissao = ( SELECT MIN(fun_3.admissao)
                                                               FROM bethadba.foempregados AS fun_3
                                                              WHERE fun_3.codi_emp = fun_2.codi_emp ) ) )     


UNION ALL 


SELECT COALESCE( String( bethadba.FOVIGENCIAS_SERVICO.codi_emp ), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.i_servicos), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.VIGENCIA), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.DESCRICAO), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.cgc), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.tipo_insc), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_terceiro), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.perc_terceiro), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.perc_inss_empresa), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.perc_acid_trabalho), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_sat), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.perc_autonomos), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_fpas), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_atividade), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_gfip), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_gps), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.i_bancos), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.numero_fgts), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.endereco), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.numero), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.bairro), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.cep), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.cidade), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.estado), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.i_filiais), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.sequencia_gps), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.filantropia), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.origem_reg), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.tipo), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codi_mun), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.codigo_municipio), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.I_FPAS), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.CALCULA_INSS_EMPRESA_LEI_12546), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_SERVICO_TOMADOR), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_ENDERECO), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.COMPLEMENTO), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_INSCRICAO_CONTRATANTE_EMPREITADA_PARCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.INSCRICAO_CONTRATANTE_EMPREITADA_PARCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.NOME_CONTRATANTE_EMPREITADA_PARCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_INSCRICAO_PROPRIETARIO_CEI_EMPREITADA_PARCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.INSCRICAO_PROPRIETARIO_CEI_EMPREITADA_PARCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.NOME_PROPRIETARIO_CEI_EMPREITADA_PARCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.I_CNAE20), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_INFORMACAO_ALIQUOTA_ACIDENTE_TRABALHO), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.I_PROCESSO), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.I_SCP), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.DDD), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TELEFONE), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.COMPETENCIA_FIM_VIGENCIA), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_LOTACAO_ESOCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.I_PROCESSO_TERCEIROS), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.CAEPF), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.TIPO_CAEPF), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.REGISTRO_PONTO), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.CONTRATACAO_APRENDIZ), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.I_PROCESSO_CONTRATACAO_APRENDIZ), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.REALIZA_CONTRATACAO_APRENDIZ_INTERMEDIO_ENTIDADE_EDUCATIVA_SEM_FINS_LUCRATIVOS), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.CODIGO_SUSPENSAO_PROCESSO_RAT), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.SOMA_CODIGOS_SUSPENSAO_TERCEIROS), 'NULO'),
        COALESCE(STRING(bethadba.FOVIGENCIAS_SERVICO.PERCENTUAL_TERCEIRO_BRUTO), 'NULO')

    FROM bethadba.FOVIGENCIAS_SERVICO
    
   WHERE bethadba.FOVIGENCIAS_SERVICO.codi_emp = '#codi_emp#'
     AND fovigencias_servico.vigencia > ( SELECT MIN(vig_2.vigencia)
                                            FROM bethadba.fovigencias_servico AS vig_2
                                           WHERE vig_2.codi_emp = fovigencias_servico.codi_emp
                                             AND vig_2.i_servicos = fovigencias_servico.i_servicos ) 

ORDER BY 1, 2, 3