SELECT COALESCE(STRING(bethadba.FOEMPREGADOS_ALTERACAO_CONTRATUAL_ENVIOS_ESOCIAL.CODI_EMP), 'NULO') AS field_1,
COALESCE(STRING(bethadba.FOEMPREGADOS_ALTERACAO_CONTRATUAL_ENVIOS_ESOCIAL.I_EMPREGADOS), 'NULO') AS field_2,
COALESCE(STRING(bethadba.FOEMPREGADOS_ALTERACAO_CONTRATUAL_ENVIOS_ESOCIAL.DATA_ALTERACAO), 'NULO') AS field_3,
COALESCE(STRING(bethadba.FOEMPREGADOS_ALTERACAO_CONTRATUAL_ENVIOS_ESOCIAL.CODI_EMP_DADOS_EVENTOS), 'NULO') AS field_4,
COALESCE(STRING(bethadba.FOEMPREGADOS_ALTERACAO_CONTRATUAL_ENVIOS_ESOCIAL.I_DADOS_EVENTOS), 'NULO') AS field_5

FROM bethadba.FOEMPREGADOS_ALTERACAO_CONTRATUAL_ENVIOS_ESOCIAL

WHERE bethadba.FOEMPREGADOS_ALTERACAO_CONTRATUAL_ENVIOS_ESOCIAL.codi_emp = '#codi_emp#'