SELECT IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.CODI_EMP), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.I_EMPREGADOS), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.I_ATESTADO_OCUPACIONAL), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.DATA), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.TIPO), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.RESULTADO), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.NOME_MEDICO), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.CRM_MEDICO), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.UF), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.DATA_VENCIMENTO), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.ORIGEM_REGISTRO), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.EXAME), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.NATUREZA), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.RESULTADO_ALTERADO), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.TIPO_RESULTADO_ALTERADO), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.TIPO_AGRAVAMENTO_RESULTADO_ALTERADO), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.ORIGEM), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.TELEFONE), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.NIS_MONITORACAO_BIOLOGICA), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.NOME_MONITORACAO_BIOLOGICA), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.CRM_MONITORACAO_BIOLOGICA), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.CODIGO_ESTADO_MONITORACAO_BIOLOGICA), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.FORMA_CONTATO_MEDICO), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.NOME_SERVICO_SAUDE_RESPONSAVEL), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.CODIGO_CNES_SERVICO_SAUDE_RESPONSAVEL), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.FORMA_CONTATO_SERVICO_SAUDE_RESPONSAVEL), 'NULO'),
  			IsNull( String(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.EMAIL_SERVICO_SAUDE_RESPONSAVEL), 'NULO'),
			COALESCE(STRING(bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.I_MEDICOS), "NULO")

    FROM bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS
    
   WHERE bethadba.FOEMPREGADOS_ATESTADOS_OCUPACIONAIS.CODI_EMP = '#codi_emp#'
   
ORDER BY 1, 2