SELECT COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.CODI_EMP), 'NULO') AS field_1,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.I_FERIAS_COLETIVAS), 'NULO') AS field_2,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.GOZO_INICIO), 'NULO') AS field_3,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.GOZO_FIM), 'NULO') AS field_4,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.ABONO_PAGA), 'NULO') AS field_5,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.ABONO_INICIO), 'NULO') AS field_6,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.ABONO_FIM), 'NULO') AS field_7,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.DATA_PAGTO), 'NULO') AS field_8,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.PAGA_AD13), 'NULO') AS field_9,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.DESCONTAR_FALTAS), 'NULO') AS field_10,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.ORIGEM_REG), 'NULO') AS field_11,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.DESCONTAR_FALTAS_NOTURNAS), 'NULO') AS field_12,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.DESCONTAR_FALTAS_SUSPENSAO), 'NULO') AS field_13,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.DESCONTAR_FALTAS_PARCIAIS), 'NULO') AS field_14,
COALESCE(STRING(bethadba.FOFERIAS_COLETIVAS.NAO_CALCULAR_ADICIONAL_MP_927), 'NULO') AS field_15

    FROM bethadba.FOFERIAS_COLETIVAS
    
   WHERE bethadba.FOFERIAS_COLETIVAS.codi_emp = '#codi_emp#'

ORDER BY 1,2