SELECT IsNull( String( bethadba.fofilhos.codi_emp), 'NULO'),
         IsNull( String( bethadba.fofilhos.i_empregados ), 'NULO'),
         IsNull( String( bethadba.fofilhos.i_filhos), 'NULO'),
         IsNull( String( bethadba.fofilhos.nome), 'NULO'),
         IsNull( String( bethadba.fofilhos.data_nascto), 'NULO'),
         IsNull( String( bethadba.fofilhos.local_nascto), 'NULO'),
         IsNull( String( bethadba.fofilhos.cartorio_registro), 'NULO'),
         IsNull( String( bethadba.fofilhos.num_reg_cart), 'NULO'),
         IsNull( String( bethadba.fofilhos.filho), 'NULO'),
         IsNull( String( bethadba.fofilhos.idade_fim_fil), 'NULO'),
         IsNull( String( bethadba.fofilhos.dependente), 'NULO'),
         IsNull( String( bethadba.fofilhos.idade_fim_dep), 'NULO'),
         IsNull( String( bethadba.fofilhos.grau_parentesco), 'NULO'),
         IsNull( String( bethadba.fofilhos.nlivro), 'NULO'),
         IsNull( String( bethadba.fofilhos.nfolha), 'NULO'),
         IsNull( String( bethadba.fofilhos.data_entrega), 'NULO'),
         IsNull( String( bethadba.fofilhos.vencto_cart_vacina), 'NULO'),
         IsNull( String( bethadba.fofilhos.vencto_atest_freq), 'NULO'),
         IsNull( String( bethadba.fofilhos.origem_reg), 'NULO'),
         IsNull( String( bethadba.fofilhos.PLANO_SAUDE_OPTANTE), 'NULO'),
         IsNull( String( bethadba.fofilhos.PLANO_SAUDE_INICIO), 'NULO'),
         IsNull( String( bethadba.fofilhos.PLANO_SAUDE_FIM), 'NULO'),
         IsNull( String( bethadba.fofilhos.PLANO_SAUDE_FIM_DETERMINADO), 'NULO'),
         IsNull( String( bethadba.fofilhos.SAL_FAM_FIM), 'NULO'),
         IsNull( String( bethadba.fofilhos.SAL_FAM_FIM_DETERMINADO), 'NULO'),
         IsNull( String( bethadba.fofilhos.DEPEND_IRRF_FIM), 'NULO'),
         IsNull( String( bethadba.fofilhos.DEPEND_IRRF_FIM_DETERMINADO), 'NULO'),
         IsNull( String( bethadba.fofilhos.DECLARACAO_NASCIDO_VIVO), 'NULO'),
         IsNull( String( bethadba.fofilhos.MATRICULA_CERTIDAO_NASCIMENTO), 'NULO'),
         IsNull( String( bethadba.fofilhos.CPF), 'NULO'),
         IsNull( String( bethadba.fofilhos.RECEBE_PENSAO_ALIMENTICIA), 'NULO'),
         IsNull( String( bethadba.fofilhos.DETERMINAR_FIM_PENSAO_ALIMENTICIA), 'NULO'),
         IsNull( String( bethadba.fofilhos.DATA_FIM_PENSAO_ALIMENTICIA), 'NULO'),
         IsNull( String( bethadba.fofilhos.GERAR_COMPENSACAO_PER_DCOMP), 'NULO'),
         IsNull( String( bethadba.fofilhos.COMPETENCIA_INICIO_COMPENSACAO_PER_DCOMP), 'NULO'),
         IsNull( String( bethadba.fofilhos.DETERMINAR_FIM_COMPENSACAO_PER_DCOMP), 'NULO'),
         IsNull( String( bethadba.fofilhos.COMPETENCIA_FIM_COMPENSACAO_PER_DCOMP), 'NULO'),
         IsNull( String( bethadba.fofilhos.POSSUI_DEFICIENCIA_FISICA_MENTAL), 'NULO')

    FROM bethadba.fofilhos
    
   WHERE bethadba.fofilhos.codi_emp = '#codi_emp#'

ORDER BY bethadba.fofilhos.codi_emp ASC, 
         bethadba.fofilhos.i_empregados ASC, 
         bethadba.fofilhos.i_filhos ASC