SELECT COALESCE(STRING(bethadba.FOEMPREGADOS_ENVIOS_ESOCIAL.codi_emp), 'NULO') AS field_1,
COALESCE(STRING(bethadba.FOEMPREGADOS_ENVIOS_ESOCIAL.i_empregados), 'NULO') AS field_2,
COALESCE(STRING(bethadba.FOEMPREGADOS_ENVIOS_ESOCIAL.CODI_EMP_DADOS_EVENTOS), 'NULO') AS field_3,
COALESCE(STRING(bethadba.FOEMPREGADOS_ENVIOS_ESOCIAL.I_DADOS_EVENTOS), 'NULO') AS field_4

FROM bethadba.FOEMPREGADOS_ENVIOS_ESOCIAL

WHERE bethadba.FOEMPREGADOS_ENVIOS_ESOCIAL.codi_emp = '#codi_emp#'