SELECT IsNull( String( bethadba.FOJORNADAS_HORARIOS.codi_emp ), 'NULO'),
        COALESCE(STRING(bethadba.FOJORNADAS_HORARIOS.I_JORNADA), 'NULO'),
        COALESCE(STRING(bethadba.FOJORNADAS_HORARIOS.SEQUENCIAL), 'NULO'),
        COALESCE(STRING(bethadba.FOJORNADAS_HORARIOS.DIA_SEMANA), 'NULO'),
        COALESCE(STRING(bethadba.FOJORNADAS_HORARIOS.I_HORARIO), 'NULO'),
        COALESCE(STRING(bethadba.FOJORNADAS_HORARIOS.ORIGEM_REG), 'NULO'),
        COALESCE(STRING(bethadba.FOJORNADAS_HORARIOS.SEQUENCIAL_DIA_SEMANA), 'NULO'),
        COALESCE(STRING(bethadba.FOJORNADAS_HORARIOS.COMPANY_ID), 'NULO')

    FROM bethadba.FOJORNADAS_HORARIOS
    
   WHERE bethadba.FOJORNADAS_HORARIOS.codi_emp = '#codi_emp#'

ORDER BY bethadba.FOJORNADAS_HORARIOS.codi_emp ASC, 
         bethadba.FOJORNADAS_HORARIOS.i_jornada ASC