SELECT IsNull( String( bethadba.FOFERIAS_GOZO.codi_emp ), 'NULO'),
         COALESCE(STRING(bethadba.FOFERIAS_GOZO.I_EMPREGADOS), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.I_FERIAS_GOZO), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.I_FERIAS_AQUISITIVOS), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.GOZO_INICIO), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.GOZO_FIM), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.ABONO_PAGA), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.ABONO_INICIO), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.ABONO_FIM), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.DATA_PAGTO), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.PAGA_AD13), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.MEDIAS_MANUAL), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.DIAS_FALTAS), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.BAIXA_PROV_FERIAS), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.BAIXA_PROV_ADICFERIAS), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.BAIXA_PROV_INSS), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.BAIXA_PROV_FGTS), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.BAIXA_PROV_PIS), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.I_PAGTO), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.DESCONTAR_FALTAS), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.I_FERIAS_COLETIVAS), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.TRANSFERIDO), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.TIPO), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.ORIGEM_REG), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.GOZO_INICIO_DN), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.GOZO_FIM_DN), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.ABONO_INICIO_DN), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.ABONO_FIM_DN), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.INICIO_AQUISITIVO), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.FIM_AQUISITIVO), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.DESCONTAR_FALTAS_NOTURNAS), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.DESCONTAR_FALTAS_SUSPENSAO), 'NULO'),
        COALESCE(STRING(bethadba.FOFERIAS_GOZO.DESCONTAR_FALTAS_PARCIAIS), 'NULO')

    FROM bethadba.FOFERIAS_GOZO
    
   WHERE bethadba.FOFERIAS_GOZO.codi_emp = '#codi_emp#'

ORDER BY 1,2,bethadba.FOFERIAS_GOZO.GOZO_INICIO