SELECT IsNull( String( bethadba.FOAFASTAMENTOS.codi_emp ), 'NULO'),
        COALESCE(STRING(bethadba.FOAFASTAMENTOS.I_EMPREGADOS), 'NULO'),
        COALESCE(STRING(bethadba.FOAFASTAMENTOS.I_AFASTAMENTOS), 'NULO'),
        COALESCE(STRING(bethadba.FOAFASTAMENTOS.DATA_REAL), 'NULO'),
        COALESCE(STRING(bethadba.FOAFASTAMENTOS.DATA_FIM), 'NULO'),
        COALESCE(STRING(bethadba.FOAFASTAMENTOS.REQ_BENEFICIO), 'NULO'),
        COALESCE(STRING(bethadba.FOAFASTAMENTOS.Dt_CALC_LEI10710), 'NULO'),
        COALESCE(STRING(bethadba.FOAFASTAMENTOS.DATA_CAT), 'NULO'),
        COALESCE(STRING(bethadba.FOAFASTAMENTOS.NUMERO_CAT), 'NULO'),
        COALESCE(STRING(bethadba.FOAFASTAMENTOS.DATA_BAIXA), 'NULO'),
        COALESCE(STRING(bethadba.FOAFASTAMENTOS.TRANSFERENCIA), 'NULO'),
        COALESCE(STRING(bethadba.FOAFASTAMENTOS.DATA_ORIGEM_TRANSF), 'NULO')

    FROM bethadba.FOAFASTAMENTOS
    
   WHERE bethadba.FOAFASTAMENTOS.codi_emp = '#codi_emp#'
     AND bethadba.foafastamentos.i_afastamentos = 8 

ORDER BY 1,2