SELECT COALESCE(STRING(bethadba.GeContador.codi_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.nome_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.rcrc_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.cpfc_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.ende_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.nume_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.bair_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.cida_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.cmun_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.cepe_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.ufed_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.fone_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.dddf_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.faxe_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.email_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.cfdf_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.tins_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.categoria_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.origem_reg), 'NULO'),
COALESCE(STRING(bethadba.GeContador.cmunrais_con), 'NULO'),
COALESCE(STRING(bethadba.GeContador.codigo_municipio), 'NULO'),
COALESCE(STRING(bethadba.GeContador.cnpj), 'NULO'),
COALESCE(STRING(bethadba.GeContador.identidade), 'NULO'),
COALESCE(STRING(bethadba.GeContador.data_exp_ident), 'NULO'),
COALESCE(STRING(bethadba.GeContador.org_exp_ident), 'NULO'),
COALESCE(STRING(bethadba.GeContador.uf_exp_ident), 'NULO'),
COALESCE(STRING(bethadba.GeContador.MATRICULA), 'NULO'),
COALESCE(STRING(bethadba.GeContador.CERTIFICADO_DIGITAL), 'NULO'),
COALESCE(STRING(bethadba.GeContador.COMPLEMENTO), 'NULO'),
COALESCE(STRING(bethadba.GeContador.UF_CRC), 'NULO'),
COALESCE(STRING(bethadba.GeContador.ACESSO_PORTAL_SEFAZ), 'NULO'),
COALESCE(STRING(bethadba.GeContador.TIPO_PESSOA_PORTAL_SEFAZ), 'NULO'),
COALESCE(STRING(bethadba.GeContador.SENHA_PORTAL_SEFAZ), 'NULO'),
COALESCE(STRING(bethadba.GeContador.TIPO_CRC_SEFAZ), 'NULO'),
COALESCE(STRING(bethadba.GeContador.DATA_VALIDADE_CRC), 'NULO'),
COALESCE(STRING(bethadba.GeContador.SEQUENCIAL_CRC), 'NULO'),
COALESCE(STRING(bethadba.GeContador.ARQUIVO_CERTIFICADO_DIGITAL), 'NULO'),
COALESCE(STRING(bethadba.GeContador.RAZAO_SOCIAL), 'NULO'),
COALESCE(STRING(bethadba.GeContador.CRC_ESCRITORIO), 'NULO'),
COALESCE(STRING(bethadba.GeContador.CERTIFICADO_DIGITAL_A3), 'NULO'),
COALESCE(STRING(bethadba.GeContador.RESPONSAVEL_LEGAL_EMPRESA_JUNTO_BASE_RFB), 'NULO')

FROM bethadba.gecontador

WHERE bethadba.gecontador.codi_con > 1

ORDER BY bethadba.gecontador.codi_con