SELECT COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.I_AGENTES_INTEGRACAO+2), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.NOME), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.DATA_CADASTRO), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.CNPJ), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.ENDERECO), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.NUMERO), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.COMPLEMENTO), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.BAIRRO), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.CEP), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.CODIGO_MUNICIPIO), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.CODIGO_PAIS), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.ORIGEM_REGISTRO), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.I_DADOS_EVENTOS_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.I_LOTE_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.STATUS_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.ENVIAR_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.INCLUSAO_VALIDADA_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.GERAR_RETIFICACAO_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOAGENTES_INTEGRACAO.PROCESSAR_EXCLUSAO_ESOCIAL), 'NULO')

FROM bethadba.FOAGENTES_INTEGRACAO

WHERE bethadba.FOAGENTES_INTEGRACAO.I_AGENTES_INTEGRACAO <> 0
