SELECT COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.I_COORDENADOR_ESTAGIO+5), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.NOME), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.DATA_CADASTRO), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.CPF), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.ORIGEM_REGISTRO), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.TIPO), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.GRAU_INSTRUCAO), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.EMAIL), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.I_DADOS_EVENTOS_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.I_LOTE_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.STATUS_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.ENVIAR_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.INCLUSAO_VALIDADA_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.GERAR_RETIFICACAO_ESOCIAL), 'NULO'),
COALESCE(STRING(bethadba.FOCOORDENADOR_ESTAGIO.PROCESSAR_EXCLUSAO_ESOCIAL), 'NULO')

FROM bethadba.FOCOORDENADOR_ESTAGIO

WHERE bethadba.FOCOORDENADOR_ESTAGIO.I_COORDENADOR_ESTAGIO <> 0