SELECT IsNull( String( bethadba.foempregados.codi_emp), 'NULO'),
         IsNull( String( bethadba.foempregados.i_empregados ), 'NULO'),
         IsNull( String( bethadba.foempregados.i_filiais), 'NULO'),
         IsNull( String( bethadba.foempregados.i_horaemp), 'NULO'),
         IsNull( String( bethadba.foempregados.nome), 'NULO'),
         IsNull( String( bethadba.foempregados.paga_contr_sind), 'NULO'),
         IsNull( String( bethadba.foempregados.opta_fgts), 'NULO'),
         IsNull( String( bethadba.foempregados.categoria), 'NULO'),
         IsNull( String( bethadba.foempregados.horas_mes), 'NULO'),
         IsNull( String( bethadba.foempregados.horas_semana), 'NULO'),
         IsNull( String( bethadba.foempregados.horas_dia), 'NULO'),
         IsNull( String( bethadba.foempregados.admissao), 'NULO'),
         IsNull( String( bethadba.foempregados.salario), 'NULO'),
         IsNull( String( bethadba.foempregados.endereco), 'NULO'),
         IsNull( String( bethadba.foempregados.complemento), 'NULO'),
         IsNull( String( bethadba.foempregados.cep), 'NULO'),
         IsNull( String( bethadba.foempregados.cidade), 'NULO'),
         IsNull( String( bethadba.foempregados.fone), 'NULO'),
         IsNull( String( bethadba.foempregados.estado), 'NULO'),
         IsNull( String( bethadba.foempregados.data_nascimento), 'NULO'),
         IsNull( String( bethadba.foempregados.venc_ferias), 'NULO'),
         IsNull( String( bethadba.foempregados.i_ccustos), 'NULO'),
         IsNull( String( bethadba.foempregados.forma_pagto), 'NULO'),
         IsNull( String( bethadba.foempregados.sexo), 'NULO'),
         IsNull( String( bethadba.foempregados.local_nascimento), 'NULO'),
         IsNull( String( bethadba.foempregados.uf_nascimento), 'NULO'),
         IsNull( String( bethadba.foempregados.estado_civil), 'NULO'),
         IsNull( String( bethadba.foempregados.nacionalidade), 'NULO'),
         IsNull( String( bethadba.foempregados.ano_chegada), 'NULO'),
         IsNull( String( bethadba.foempregados.identidade), 'NULO'),
         IsNull( String( bethadba.foempregados.naturalizado), 'NULO'),
         IsNull( String( bethadba.foempregados.pis), 'NULO'),
         IsNull( String( bethadba.foempregados.cpf), 'NULO'),
         IsNull( String( bethadba.foempregados.cart_prof), 'NULO'),
         IsNull( String( bethadba.foempregados.serie_cart_prof), 'NULO'),
         IsNull( String( bethadba.foempregados.opcao_fgts), 'NULO'),
         IsNull( String( bethadba.foempregados.conta_fgts), 'NULO'),
         IsNull( String( NULL ), 'NULO'),
         IsNull( String( bethadba.foempregados.venc_exame_medico), 'NULO'),
         IsNull( String( bethadba.foempregados.vinculo), 'NULO'),
         IsNull( String( bethadba.foempregados.i_bancos), 'NULO'),
         IsNull( String( bethadba.foempregados.conta_corr), 'NULO'),
         IsNull( String( bethadba.foempregados.i_cargos), 'NULO'),
         IsNull( String( bethadba.foempregados.data_base), 'NULO'),
         IsNull( String( bethadba.foempregados.cart_motorista), 'NULO'),
         IsNull( String( bethadba.foempregados.categ_cart_mot), 'NULO'),
         IsNull( String( bethadba.foempregados.venc_cart_mot), 'NULO'),
         IsNull( String( bethadba.foempregados.data_transf), 'NULO'),
         IsNull( String( bethadba.foempregados.sai_rais), 'NULO'),
         IsNull( String( bethadba.foempregados.grau_instrucao), 'NULO'),
         IsNull( String( bethadba.foempregados.i_depto), 'NULO'),
         IsNull( String( bethadba.foempregados.emprego_ant), 'NULO'),
         IsNull( String( bethadba.foempregados.nome_pai), 'NULO'),
         IsNull( String( bethadba.foempregados.nome_mae), 'NULO'),
         IsNull( String( bethadba.foempregados.uf_cart_prof), 'NULO'),
         IsNull( String( bethadba.foempregados.i_sindicatos), 'NULO'),
         IsNull( String( bethadba.foempregados.org_exp_ident), 'NULO'),
         IsNull( String( bethadba.foempregados.uf_exp_ident), 'NULO'),
         IsNull( String( bethadba.foempregados.dt_exp_ident), 'NULO'),
         IsNull( String( bethadba.foempregados.dt_exp_cprof), 'NULO'),
         IsNull( String( bethadba.foempregados.tipo_visto_estrangeiro), 'NULO'),
         IsNull( String( bethadba.foempregados.validade_id_estr), 'NULO'),
         IsNull( String( bethadba.foempregados.validade_ctrab_estr), 'NULO'),
         IsNull( String( bethadba.foempregados.grupo_sanguineo), 'NULO'),
         IsNull( String( bethadba.foempregados.rh_sanguineo), 'NULO'),
         IsNull( String( bethadba.foempregados.nome_conjuge), 'NULO'),
         IsNull( String( bethadba.foempregados.ultimo_exame_medico), 'NULO'),
         IsNull( String( bethadba.foempregados.i_conselhos), 'NULO'),
         IsNull( String( bethadba.foempregados.num_reg_cons_reg), 'NULO'),
         IsNull( String( bethadba.foempregados.regiao_reg_cons_regional), 'NULO'),
         IsNull( String( bethadba.foempregados.i_estabilidade), 'NULO'),
         IsNull( String( bethadba.foempregados.inicio_estabilidade), 'NULO'),
         IsNull( String( bethadba.foempregados.fim_estabilidade), 'NULO'),
         IsNull( String( bethadba.foempregados.i_localtrab), 'NULO'),
         IsNull( String( bethadba.foempregados.titulo_eleit), 'NULO'),
         IsNull( String( bethadba.foempregados.zona_eleit), 'NULO'),
         IsNull( String( bethadba.foempregados.secao_eleit), 'NULO'),
         IsNull( String( bethadba.foempregados.dcad_pis), 'NULO'),
         IsNull( String( bethadba.foempregados.i_servicos), 'NULO'),
         IsNull( String( bethadba.foempregados.ini_praz_det), 'NULO'),
         IsNull( String( bethadba.foempregados.fim_praz_det), 'NULO'),
         IsNull( String( bethadba.foempregados.possui_vinc_out_emp), 'NULO'),
         IsNull( String( bethadba.foempregados.empresa_outro_vinc), 'NULO'),
         IsNull( String( bethadba.foempregados.codigo_vinc_outra_emp), 'NULO'),
         IsNull( String( bethadba.foempregados.ult_cont_sind), 'NULO'),
         IsNull( String( bethadba.foempregados.oco_sefip), 'NULO'),
         IsNull( String( bethadba.foempregados.cor), 'NULO'),
         IsNull( String( bethadba.foempregados.cart_reservista), 'NULO'),
         IsNull( String( bethadba.foempregados.cate_reservista), 'NULO'),
         IsNull( String( bethadba.foempregados.i_niveis), 'NULO'),
         IsNull( String( bethadba.foempregados.i_clasniveis), 'NULO'),
         IsNull( String( bethadba.foempregados.i_refeniveis), 'NULO'),
         IsNull( String( bethadba.foempregados.matricula), 'NULO'),
         IsNull( String( bethadba.foempregados.deficiente_fisico), 'NULO'),
         IsNull( String( bethadba.foempregados.matric_inss), 'NULO'),
         IsNull( String( bethadba.foempregados.tipo_contrib), 'NULO'),
         IsNull( String( bethadba.foempregados.contrib_indiv), 'NULO'),
         IsNull( String( bethadba.foempregados.inicio_contribuicao), 'NULO'),
         IsNull( String( bethadba.foempregados.classe_atual), 'NULO'),
         IsNull( String( bethadba.foempregados.data_classe), 'NULO'),
         IsNull( String( bethadba.foempregados.troca_aut_clas), 'NULO'),
         IsNull( String( bethadba.foempregados.evento_prolabore), 'NULO'),
         IsNull( String( bethadba.foempregados.gps_trimestral), 'NULO'),
         IsNull( String( bethadba.foempregados.gps_deducao), 'NULO'),
         IsNull( String( bethadba.foempregados.i_contribuintes), 'NULO'),
         IsNull( String( bethadba.foempregados.tipo_epr), 'NULO'),
         IsNull( String( bethadba.foempregados.usa_sist), 'NULO'),
         IsNull( String( bethadba.foempregados.tempermuta), 'NULO'),
         IsNull( String( bethadba.foempregados.i_turmas), 'NULO'),
         IsNull( String( bethadba.foempregados.relogio1), 'NULO'),
         IsNull( String( bethadba.foempregados.relogio2), 'NULO'),
         IsNull( String( bethadba.foempregados.relogio3), 'NULO'),
         IsNull( String( bethadba.foempregados.relogio4), 'NULO'),
         IsNull( String( bethadba.foempregados.relogio5), 'NULO'),
         IsNull( String( bethadba.foempregados.aco_nao_aut), 'NULO'),
         IsNull( String( bethadba.foempregados.codigo_exportacao), 'NULO'),
         IsNull( String( bethadba.foempregados.transf_codi_emp), 'NULO'),
         IsNull( String( bethadba.foempregados.transf_i_empregados), 'NULO'),
         IsNull( String( bethadba.foempregados.regime_trabalho), 'NULO'),
         IsNull( String( bethadba.foempregados.pis_domi_banc), 'NULO'),
         IsNull( String( bethadba.foempregados.pis_num_banco), 'NULO'),
         IsNull( String( bethadba.foempregados.pis_agencia), 'NULO'),
         IsNull( String( bethadba.foempregados.pis_agencia_dv), 'NULO'),
         IsNull( String( bethadba.foempregados.pis_end_banco), 'NULO'),
         IsNull( String( bethadba.foempregados.autoriza_tf), 'NULO'),
         IsNull( String( bethadba.foempregados.tipo_valor_tf), 'NULO'),
         IsNull( String( bethadba.foempregados.valor_tf), 'NULO'),
         IsNull( String( bethadba.foempregados.data_emissao_tf), 'NULO'),
         IsNull( String( bethadba.foempregados.matricula_tf), 'NULO'),
         IsNull( String( bethadba.foempregados.bairro), 'NULO'),
         IsNull( String( bethadba.foempregados.sindicalizado), 'NULO'),
         IsNull( String( bethadba.foempregados.numero_end), 'NULO'),
         IsNull( String( bethadba.foempregados.imprime_recibo), 'NULO'),
         IsNull( String( bethadba.foempregados.origem_reg), 'NULO'),
         IsNull( String( bethadba.foempregados.fone2), 'NULO'),
         IsNull( String( bethadba.foempregados.tipo_servico), 'NULO'),
         IsNull( String( bethadba.foempregados.contr_exper), 'NULO'),
         IsNull( String( bethadba.foempregados.pro_praz_det), 'NULO'),
         IsNull( String( bethadba.foempregados.contr_sobre_sal_min), 'NULO'),
         IsNull( String( bethadba.foempregados.contr_sobre_sal_min_data), 'NULO'),
         IsNull( String( bethadba.foempregados.simples_072007), 'NULO'),
         IsNull( String( bethadba.foempregados.DATA_CALC_AFASTAMENTOS), 'NULO'),
         IsNull( String( bethadba.foempregados.I_AFASTAMENTOS), 'NULO'),
         IsNull( String( bethadba.foempregados.ALVARA_JUDICIAL), 'NULO'),
         IsNull( String( bethadba.foempregados.I_OPERADORAPLANOSAUDE), 'NULO'),
         IsNull( String( bethadba.foempregados.PLANO_SAUDE_OPTANTES), 'NULO'),
         IsNull( String( bethadba.foempregados.OPCAO_PLANO_SAUDE), 'NULO'),
         IsNull( String( bethadba.foempregados.TIPO_CLA_ASSEC_DIR_REC_RES_ANT), 'NULO'),
         IsNull( String( bethadba.foempregados.TIPO_CONTA), 'NULO'),
         IsNull( String( bethadba.foempregados.DATA_REINTEGRACAO), 'NULO'),
         IsNull( String( bethadba.foempregados.TIPO_INSCRICAO_FILIAL_ORIGEM), 'NULO'),
         IsNull( String( bethadba.foempregados.INSCRICAO_FILIAL_ORIGEM), 'NULO'),
         IsNull( String( bethadba.foempregados.MATRICULA_ORIGEM), 'NULO'),
         IsNull( String( bethadba.foempregados.NOME_EMPRESA_ORIGEM), 'NULO'),
         IsNull( String( bethadba.foempregados.EMAIL), 'NULO'),
         IsNull( String( bethadba.foempregados.NUMERO_PROCESSO_MTE), 'NULO'),
         IsNull( String( bethadba.foempregados.DATA_CHEGADA), 'NULO'),
         IsNull( String( bethadba.foempregados.DATA_NATURALIZACAO), 'NULO'),
         IsNull( String( bethadba.foempregados.CASADO_BRASILEIRO), 'NULO'),
         IsNull( String( bethadba.foempregados.FILHOS_BRASILEIRO), 'NULO'),
         IsNull( String( bethadba.foempregados.NIF), 'NULO'),
         IsNull( String( bethadba.foempregados.NUMERO_RIC), 'NULO'),
         IsNull( String( bethadba.foempregados.ORGAO_EMISSOR_RIC), 'NULO'),
         IsNull( String( bethadba.foempregados.LOCAL_RIC), 'NULO'),
         IsNull( String( bethadba.foempregados.DATA_EXPEDICAO_RIC), 'NULO'),
         IsNull( String( bethadba.foempregados.DATA_VALIDADE_RIC), 'NULO'),
         IsNull( String( bethadba.foempregados.DIGITO_CONTA_PAGAMENTO), 'NULO'),
         IsNull( String( bethadba.foempregados.RESIDENTE_EXTERIOR), 'NULO'),
         IsNull( String( bethadba.foempregados.TIPO_ENDERECO), 'NULO'),
         CASE WHEN foempregados.MUNICIPIO_ENDERECO > 5570 THEN 'NULO' ELSE IsNull( String( bethadba.foempregados.MUNICIPIO_ENDERECO), 'NULO') END,
         CASE WHEN foempregados.MUNICIPIO_NASCIMENTO > 5570 THEN 'NULO' ELSE IsNull( String( bethadba.foempregados.MUNICIPIO_NASCIMENTO), 'NULO') END,
         IsNull( String( bethadba.foempregados.PAIS_ENDERECO), 'NULO'),
         IsNull( String( bethadba.foempregados.PAIS_NASCIMENTO), 'NULO'),
         IsNull( String( bethadba.foempregados.BENEFICIADO_PAT), 'NULO'),
         IsNull( String( bethadba.foempregados.CONTR_SOBRE_SAL_MIN_TIPO), 'NULO'),
         IsNull( String( bethadba.foempregados.GPS_CONJUNTA_NOVEMBRO_13_INTEGRAL), 'NULO'),
         IsNull( String( bethadba.foempregados.GPS_CONJUNTA_NOVEMBRO_13_INTEGRAL_INICIO), 'NULO'),
         IsNull( String( bethadba.foempregados.BENEFICIADO_PAT_SERVICO_PROPRIO), 'NULO'),
         IsNull( String( bethadba.foempregados.BENEFICIADO_PAT_ADMINISTRACAO_COZINHAS), 'NULO'),
         IsNull( String( bethadba.foempregados.BENEFICIADO_PAT_REFEICAO_CONVENIO), 'NULO'),
         IsNull( String( bethadba.foempregados.BENEFICIADO_PAT_REFEICOES_TRANSPORTADAS), 'NULO'),
         IsNull( String( bethadba.foempregados.BENEFICIADO_PAT_CESTA_ALIMENTOS), 'NULO'),
         IsNull( String( bethadba.foempregados.BENEFICIADO_PAT_ALIMENTACAO_CONVENIO), 'NULO'),
         IsNull( String( bethadba.foempregados.ATIVIDADE_CONTA_PROPRIA_RURAL), 'NULO'),
         IsNull( String( bethadba.foempregados.NUMERO_PASSAPORTE), 'NULO'),
         IsNull( String( bethadba.foempregados.EMISSOR_PASSAPORTE), 'NULO'),
         IsNull( String( bethadba.foempregados.UF_PASSAPORTE), 'NULO'),
         IsNull( String( bethadba.foempregados.DATA_EMISSAO_PASSAPORTE), 'NULO'),
         IsNull( String( bethadba.foempregados.DATA_VALIDADE_PASSAPORTE), 'NULO'),
         IsNull( String( bethadba.foempregados.PAIS_PASSAPORTE), 'NULO'),
         IsNull( String( bethadba.foempregados.TIPO_INDICATIVO_ADMISSAO), 'NULO'),
         IsNull( String( bethadba.foempregados.NOME_MUNICIPIO_RESIDENTE_EXTERIOR), 'NULO'),
         IsNull( String( bethadba.foempregados.PAIS_NACIONALIDADE), 'NULO'),
         IsNull( String( bethadba.foempregados.DATA_EXPEDICAO_CNH), 'NULO'),
         IsNull( String( bethadba.foempregados.ORGAO_EMISSOR_CNH), 'NULO'),
         IsNull( String( bethadba.foempregados.CODIGO_POSTAL), 'NULO'),
         IsNull( String( bethadba.foempregados.RESIDENCIA_PROPRIA), 'NULO'),
         IsNull( String( bethadba.foempregados.IMOVEL_ADQUIRIDO_RECURSOS_FGTS), 'NULO'),
         IsNull( String( bethadba.foempregados.EMAIL_ALTERNATIVO), 'NULO'),
         IsNull( String( bethadba.foempregados.TIPO_PROCESSO_ALVARA), 'NULO'),
         IsNull( String( bethadba.foempregados.AUTORIA_ALVARA), 'NULO'),
         IsNull( String( bethadba.foempregados.NUMERO_ALVARA), 'NULO'),
         IsNull( String( bethadba.foempregados.INDICATIVO_DECISAO_ALVARA), 'NULO'),
         IsNull( String( bethadba.foempregados.DATA_DECISAO_ALVARA), 'NULO'),
         IsNull( String( bethadba.foempregados.MONTANTE_INTEGRAL_DEPOSITADO_ALVARA), 'NULO'),
         IsNull( String( bethadba.foempregados.INICIO_VIGENCIA_ALVARA), 'NULO'),
         IsNull( String( bethadba.foempregados.FIM_VIGENCIA_ALVARA), 'NULO'),
         IsNull( String( bethadba.foempregados.IDENTIFICACAO_ALVARA), 'NULO'),
         IsNull( String( bethadba.foempregados.CODIGO_MUNICIPIO_ALVARA), 'NULO'),
         IsNull( String( bethadba.foempregados.POSSUI_DEFICIENCIA), 'NULO'),
         IsNull( String( bethadba.foempregados.POSSUI_DEFICIENCIA_MOTORA), 'NULO'),
         IsNull( String( bethadba.foempregados.POSSUI_DEFICIENCIA_VISUAL), 'NULO'),
         IsNull( String( bethadba.foempregados.POSSUI_DEFICIENCIA_AUDITIVA), 'NULO'),
         IsNull( String( bethadba.foempregados.POSSUI_DEFICIENCIA_OUTRAS), 'NULO'),
         IsNull( String( bethadba.foempregados.POSSUI_DEFICIENCIA_REABILITADO), 'NULO'),
         IsNull( String( bethadba.foempregados.OBSERVACAO_DEFICIENCIA), 'NULO'),
         IsNull( String( bethadba.foempregados.I_FUNCAO), 'NULO'),
         IsNull( String( bethadba.foempregados.NUMERO_RNE), 'NULO'),
         IsNull( String( bethadba.foempregados.DATA_EXPEDICAO_RNE), 'NULO'),
         IsNull( String( bethadba.foempregados.ORGAO_EMISSOR_RNE),'NULO'),
         COALESCE( String( bethadba.foempregados.ENDERECO_COMERCIAL),'NULO'),
         COALESCE( String( bethadba.foempregados.I_PROCESSO),'NULO'),
         COALESCE( String( bethadba.foempregados.CODIGO_SCE_DOMINIO_ATENDIMENTO),'NULO'),
         COALESCE( String( bethadba.foempregados.I_INSTITUICAO_ENSINO),'NULO'),
         COALESCE( String( bethadba.foempregados.I_AGENTES_INTEGRACAO),'NULO'),
         COALESCE( String( bethadba.foempregados.I_COORDENADOR_ESTAGIO),'NULO'),
         COALESCE( String( bethadba.foempregados.AREA_ATUACAO_ESTAGIARIO),'NULO'),
         COALESCE( String( bethadba.foempregados.NATUREZA_ESTAGIO),'NULO'),
         COALESCE( String( bethadba.foempregados.NIVEL_ESTAGIO),'NULO'),
         COALESCE( String( bethadba.foempregados.APOLICE_SEGURO_ESTAGIARIO),'NULO'),
         COALESCE( String( bethadba.foempregados.POSSUI_DEFICIENCIA_MENTAL),'NULO'),
         COALESCE( String( bethadba.foempregados.I_JORNADA),'NULO'),
         COALESCE( String( bethadba.foempregados.SITUACAO_QUALIFICACAO_CADASTRAL_INSS_RECEITA_FEDERAL),'NULO'),
         COALESCE( String( bethadba.foempregados.CAIXA_POSTAL),'NULO'),
         COALESCE( String( bethadba.foempregados.CEP_CAIXA_POSTAL),'NULO'),
         COALESCE( String( bethadba.foempregados.MOTIVO_CONTRATACAO_TRABALHO_TEMPORARIO),'NULO'),
         COALESCE( String( bethadba.foempregados.NOME_TRABALHADOR_SUBSTITUIDO_TRABALHO_TEMPORARIO),'NULO'),
         COALESCE( String( bethadba.foempregados.CPF_TRABALHADOR_SUBSTITUIDO_TRABALHO_TEMPORARIO),'NULO'),
         COALESCE( String( bethadba.foempregados.MATRICULA_TRABALHADOR_SUBSTITUIDO_TRABALHO_TEMPORARIO),'NULO'),
         COALESCE( String( bethadba.foempregados.TIPO_HORARIO),'NULO'),
         COALESCE( String( bethadba.foempregados.CODIGO_ESOCIAL ),'NULO'),
         COALESCE( String( bethadba.foempregados.I_REMUNERACAO_VARIAVEL),'NULO'),
         COALESCE( String( bethadba.foempregados.I_PROCESSO_REINTEGRACAO),'NULO'),
         COALESCE( String( bethadba.foempregados.POSSUI_REDUCAO_ALIQUOTA_INSS),'NULO'),
         COALESCE( String( bethadba.foempregados.POSSUI_REDUCAO_ALIQUOTA_INSS_COMPETENCIA),'NULO'),
         COALESCE( String( bethadba.foempregados.QUANTIDADE_DIAS_CONTRATO_EXPERIENCIA),'NULO'),
         COALESCE( String( bethadba.foempregados.QUANTIDADE_DIAS_PRORROGACAO_CONTRATO_EXPERIENCIA),'NULO'),
         COALESCE( String( bethadba.foempregados.RECEBIA_SEGURO_DESEMPREGO),'NULO'),
         COALESCE( String( bethadba.foempregados.NATUREZA_TRABALHO_AUTONOMO),'NULO'),
         COALESCE( String( bethadba.foempregados.DDD_FONE),'NULO'),
         COALESCE( String( bethadba.foempregados.DDD_FONE2),'NULO'),
         COALESCE( String( bethadba.foempregados.DDD_CELULAR),'NULO'),
         COALESCE( String( bethadba.foempregados.CELULAR),'NULO'),
         COALESCE( String( bethadba.foempregados.DDD_CONTATO_2),'NULO'),
         COALESCE( String( bethadba.foempregados.CONTATO_2),'NULO'),
         COALESCE( String( bethadba.foempregados.INSCRICAO_MUNICIPAL_AUTONOMO),'NULO'),
         COALESCE( String( bethadba.foempregados.REGIME_CASAMENTO),'NULO'),
         COALESCE( String( bethadba.foempregados.DIRIGENTE_SINDICAL),'NULO'),
         COALESCE( String( bethadba.foempregados.CNPJ_EMPRESA_ORIGEM_DIRIGENTE_SINDICAL),'NULO'),
         COALESCE( String( bethadba.foempregados.NOME_EMPRESA_ORIGEM_DIRIGENTE_SINDICAL),'NULO'),
         COALESCE( String( bethadba.foempregados.CATEGORIA_ORIGEM_DIRIGENTE_SINDICAL),'NULO'),
         COALESCE( String( bethadba.foempregados.DATA_ADMISSAO_EMPRESA_ORIGEM_DIRIGENTE_SINDICAL),'NULO'),
         COALESCE( String( bethadba.foempregados.MATRICULA_EMPRESA_ORIGEM_DIRIGENTE_SINDICAL),'NULO'),
         COALESCE( String( bethadba.foempregados.RESPONSAVEL_REMUNERACAO_DIRIGENTE_SINDICAL),'NULO'),
         COALESCE( String( bethadba.foempregados.TIPO_REMUNERACAO_DIRIGENTE_SINDICAL),'NULO'),
         COALESCE( String( bethadba.foempregados.DATA_INICIO_PAGAMENTO_ADICIONAL_DIRIGENTE_SINDICAL),'NULO'),
         COALESCE( String( bethadba.foempregados.REMUNERACAO_SINDICATO_DIRIGENTE_SINDICAL),'NULO'),
         COALESCE( String( bethadba.foempregados.REMUNERACAO_EMPRESA_DIRIGENTE_SINDICAL),'NULO'),
         COALESCE( String( bethadba.foempregados.ORGAO_EXPEDICAO_RG),'NULO'),
         COALESCE( String( bethadba.foempregados.FORMA_CALCULO),'NULO'),
         COALESCE( String( bethadba.foempregados.USA_SALARIO_MINIMO_ESTADUAL),'NULO'),
         COALESCE( String( bethadba.foempregados.I_TABCALC_SALARIO_MINIMO_ESTADUAL),'NULO'),
         COALESCE( String( bethadba.foempregados.I_CATEGORIA_SALARIO_MINIMO_ESTADUAL),'NULO'),
         COALESCE( String( bethadba.foempregados.EMPRESA_ORIGEM_DESONERADA),'NULO'),
         COALESCE( String( bethadba.foempregados.REMUNERACAO_PERIODO_DESLIGAMENTO_REINTEGRACAO_PAGAS_JUIZO),'NULO'),
         COALESCE( String( bethadba.foempregados.CODIGO_MUNICIPIO_RIC),'NULO'),
         COALESCE( String( bethadba.foempregados.CODIGO_UF_CARTEIRA_MOTORISTA),'NULO'),
         COALESCE( String( bethadba.foempregados.DATA_PRIMEIRA_HABILITACAO_CARTEIRA_MOTORISTA),'NULO'),
         COALESCE( String( bethadba.foempregados.BRASILEIRO_NASCIDO_EXTERIOR),'NULO'),
         COALESCE( String( bethadba.foempregados.CALCULAR_INSS_PATRONAL),'NULO'),
         COALESCE( String( bethadba.foempregados.CARGA_HORARIA_VARIAVEL),'NULO'),
         COALESCE( String( bethadba.foempregados.DATA_OPERACAO_CONECTIVIDADE_SOCIAL),'NULO'),
         COALESCE( String( bethadba.foempregados.CHAVE_IDENTIFICACAO_CONECTIVIDADE_SOCIAL),'NULO'),
         COALESCE( String( bethadba.foempregados.DATA_REAL_DN_AFASTAMENTO_DA),'NULO'),
         COALESCE( String( bethadba.foempregados.CALCULAR_ADIANTAMENTO_SALARIAL),'NULO'),
         COALESCE( String( bethadba.foempregados.CALCULO_ADIANTAMENTO_SALARIAL_PERCENTUAL),'NULO'),
         COALESCE( String( bethadba.foempregados.TIPO_INSCRICAO_EMPRESA_ORIGEM_DIRIGENTE_SINDICAL),'NULO'),
         COALESCE( String( bethadba.foempregados.UF_BASE_CONTA_FGTS),'NULO'),
         COALESCE( String( bethadba.foempregados.HORAS_COMPENSADAS),'NULO'),
         COALESCE( String( bethadba.foempregados.NUMERO_LIVRO_REGISTRO),'NULO'),
         COALESCE( String( bethadba.foempregados.NUMERO_FOLHA_LIVRO_REGISTRO),'NULO'),
         COALESCE( String( bethadba.foempregados.NOME_SOCIAL),'NULO'),
         COALESCE( String( bethadba.foempregados.APOSENTADO),'NULO'),
         COALESCE( String( bethadba.foempregados.POSSUI_DEFICIENCIA_INTELECTUAL),'NULO'),
         COALESCE( String( bethadba.foempregados.COTA_DIFICIENTE),'NULO'),
         COALESCE( String( bethadba.foempregados.I_SUPERVISOR_ESTAGIO),'NULO'),
         COALESCE( String( bethadba.foempregados.MOTIVO_PRORROGACAO_CONTRATO_EXPERIENCIA),'NULO'),
         COALESCE( String( bethadba.foempregados.DESCONTAR_ESTOURO_RESCISAO_EMPRESA_ORIGEM),'NULO'),
         COALESCE( String( bethadba.foempregados.DESCONTAR_CONTRIBUICAO_SINDICAL_A_PARTIR_11_2017),'NULO'),
         COALESCE( String( bethadba.foempregados.COMP_INICIO_DESCONTO_CONTRIBUICAO_SINDICAL_A_PARTIR_11_2017),'NULO'),
         COALESCE( String( bethadba.foempregados.PAGA_CONTR_SIND_11_2017),'NULO')

    FROM bethadba.foempregados
    
   WHERE bethadba.foempregados.codi_emp IN (#codi_emp_list#)
     AND bethadba.foempregados.transf_codi_emp IS NOT NULL
     AND bethadba.foempregados.transf_codi_emp < bethadba.foempregados.codi_emp

ORDER BY bethadba.foempregados.codi_emp, bethadba.foempregados.i_empregados